
[font]

normal.family = "FiraCode Nerd Font Mono"
bold.family = "FiraCode Nerd Font Mono"
italic.family = "FiraCode Nerd Font Mono"
bold_italic.family = "FiraCode Nerd Font Mono"
offset.y = 6
glyph_offset.y = 3
size = 12.0

[window]

padding.x = 0
padding.y = 0
decorations = "Full"

[colors]

cursor.text = "#111111"
cursor.cursor = "#ffffff"
vi_mode_cursor.text = "#111111"
vi_mode_cursor.cursor = "#ffffff"

